# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-10 21:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ebullition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ebu_detail', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Empatage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_detail', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Etape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Etape_ebullition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ebullition', models.CharField(max_length=256)),
                ('label_ebullition', models.CharField(default='Label', max_length=100)),
                ('detail_ebullition', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Etape_empatage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_empatage', models.CharField(max_length=256)),
                ('label_empatage', models.CharField(default='Label', max_length=100)),
                ('detail_empatage', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Etape_fermentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fermentation', models.CharField(max_length=256)),
                ('label_fermentation', models.CharField(default='Label', max_length=100)),
                ('detail_fermentation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fermentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ferm_detail', models.CharField(max_length=150)),
                ('ferm_tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Etape_fermentation')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('quantite', models.CharField(max_length=100)),
                ('typ', models.CharField(max_length=100)),
                ('caracteristique', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Methode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('label', models.CharField(default='Label', max_length=100)),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos_brassins')),
                ('thumbnail', models.ImageField(blank=True, max_length=500, null=True, upload_to='photos_brassins')),
            ],
        ),
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('real_date', models.DateField(null=True)),
                ('volume', models.IntegerField(null=True)),
                ('dens_init', models.IntegerField(null=True)),
                ('dens_final', models.IntegerField(null=True)),
                ('color', models.IntegerField(null=True)),
                ('amertume', models.IntegerField(null=True)),
                ('alcool', models.IntegerField(null=True)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Methode')),
                ('user', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='recette',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Recette'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recette',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Recette'),
        ),
        migrations.AddField(
            model_name='fermentation',
            name='recette',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Recette'),
        ),
        migrations.AddField(
            model_name='etape',
            name='recette',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Recette'),
        ),
        migrations.AddField(
            model_name='empatage',
            name='emp_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Etape_empatage'),
        ),
        migrations.AddField(
            model_name='empatage',
            name='recette',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Recette'),
        ),
        migrations.AddField(
            model_name='ebullition',
            name='ebu_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Etape_ebullition'),
        ),
        migrations.AddField(
            model_name='ebullition',
            name='recette',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Recette'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='recette',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Recette'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
